//---------------------------------------------------------------
// Font generated by muGUI Font and Bitmap Generator (v.0.1.0.1), 
// available from http://www.muGUI.de
//
// Template for HiTech code, see http://edeca.net/wp/?p=874
//
// Project Name:  New Project
//---------------------------------------------------------------
#ifndef FONT_TAHOMA_H
#define FONT_TAHOMA_H
//---------------------------------------------------------------
// Group Name: Tahoma10
// Designer: Imported System Font
// Date: 12 Nov 2011
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 11 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
//extern unsigned char Tahoma10[];

//---------------------------------------------------------------
// Group Name: Tahoma16
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 21 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
//extern unsigned char Tahoma16[];

//---------------------------------------------------------------
// Group Name: Tahoma14
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 19 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern unsigned char Tahoma14[];
//---------------------------------------------------------------
// Group Name: Tahoma12
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 16 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern unsigned char Tahoma12[];
//---------------------------------------------------------------
// Group Name: Tahoma8
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 11 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
//extern unsigned char Tahoma8[];
//---------------------------------------------------------------
// Group Name: Tahoma7
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 11 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
extern unsigned char Tahoma7[];

//---------------------------------------------------------------
// Group Name: Tahoma32
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 44 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
//extern unsigned char Tahoma32[];
//
//---------------------------------------------------------------
// Group Name: Tahoma26
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 35 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
//extern unsigned char Tahoma26[];
//
//---------------------------------------------------------------
// Group Name: Tahoma22
// Designer: Imported System Font
// Date: 19 Feb 2012
// Description: Imported System Font
// Byte Orientation: verticalCeiling
// Font Height: 29 pixel(s)
// Font Type: Proportional 
// Font Width: Individual 
// Number of Bitmaps: 95
// Start Character: 32 " "
// Stop Character: 126 "~"
//---------------------------------------------------------------
//extern unsigned char Tahoma22[]; 

#endif //TAHOMA_H
